# Generated by Django 5.2.1 on 2026-01-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ex03', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movies',
            name='opening_crawl',
            field=models.TextField(null=True),
        ),
    ]
