#!/bin/python3
import sys
import antigravity

https://geohashing.site/geohashing/The_Algorithm
https://www.google.com/search?q=geohash+python+without+library&sca_esv=0ccf53d8b4904cec&sxsrf=AE3TifOhuLzLtdcfRZtCeqLI3HynnsLpIA%3A1766073069386&ei=7SJEac2zF5OdkdUPqM-0wAM&oq=geohash+python+without+li&gs_lp=Egxnd3Mtd2l6LXNlcnAiGWdlb2hhc2ggcHl0aG9uIHdpdGhvdXQgbGkqAggAMgUQIRigATIFECEYoAEyBRAhGKABSIYoUNYFWIUYcAF4AJABAJgBfqABgwqqAQMzLjm4AQPIAQD4AQGYAgygAtsJwgIKEAAYsAMY1gQYR8ICBhAAGBYYHsICCBAAGIAEGKIEwgIIEAAYogQYiQXCAgUQABjvBcICBBAhGBXCAgsQABiABBiGAxiKBcICBxAhGKABGArCAgYQIRgVGA3CAgUQIRifBZgDAIgGAZAGCJIHBDEuMTGgB9otsgcEMC4xMbgH1wnCBwYwLjEwLjLIBxqACAA&sclient=gws-wiz-serp
https://xkcd.com/426/